version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: mindLab_database
    environment:
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'
    ports:
      - '${DB_PORT}:${DB_PORT}'
    env_file:
      - .env
